version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
  frontend:
    image: nginx:stable-alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - '8080:80'
